#!/bin/bash

# Define your repository URL and branch
repository_url="https://github.com/Jude-Amahiri/alx-low_level_programming.git"
branch="main"

# Prompt for the commit message
read -p "Enter a commit message: " commit_message

# Add all changes
git add .

# Commit with the provided message
git commit -m "$commit_message"

# Push to the remote repository
git push origin $branch

